export const products = [
  { id: "app-autocad", title: "AutoCAD (WIN & MAC)", category: "Engineering", os: "Win & Mac", versions: "2015 - 2016 - 2017 - 2018 - 2019 - 2020 - 2021 - 2022 - 2023 - 2024 - 2025 - 2026", price: 15000, originalPrice: 30000, rating: 4.9, sales: 27, imageUrl: "/assets/logos/autocad.png", catalogImageUrl: "/assets/katalogAutocad.png", color: "#e11d48", specs: ["FULL VERSION", "BUKAN TRIAL", "BEBAS UPDATE", "INSTAL MUDAH", "BEBAS VIRUS"] },
  { id: "app-photoshop", title: "Adobe Photoshop (WIN & MAC)", category: "Design", os: "Win & Mac", versions: "2025 - 2024 - 2023 - 2022 - 2021 - 2020 - 2019 - CS6", price: 15000, originalPrice: 30000, rating: 4.9, sales: 24, imageUrl: "/assets/logos/photoshop.png", catalogImageUrl: "/assets/katalogPhotoshop.png", color: "#0284c7", specs: ["FULL VERSION", "FITUR LENGKAP", "BEBAS UPDATE", "INSTAL MUDAH", "BEBAS VIRUS"] },
  { id: "app-sketchup", title: "SketchUp Pro + Vray & Enscape (WIN & MAC)", category: "Engineering", os: "Win & Mac", versions: "2015 - 2016 - 2017 - 2018 - 2019 - 2020 - 2021 - 2022 - 2023 - 2024 - 2025", price: 15000, originalPrice: 30000, rating: 4.9, sales: 20, imageUrl: "/assets/logos/sketchpp.png", catalogImageUrl: "/assets/KatalogSketchup.png", color: "#0f9bd7", specs: ["INCLUDE VRAY", "ENSCAPE", "3D WAREHOUSE", "FREE EXTENSION", "BONUS MATERIAL"] },
  { id: "app-davinci", title: "DaVinci Resolve Studio + Project (WIN & MAC)", category: "Video", os: "Win & Mac", versions: "14 - 15 - 16 - 17 - 18 - 19 - 20 Studio", price: 15000, originalPrice: 30000, rating: 4.9, sales: 18, imageUrl: "/assets/logos/davinci.png", catalogImageUrl: "/assets/katalogDavinci.png", color: "#0f766e", specs: ["FULL VERSION", "FITUR LENGKAP", "BEBAS UPDATE", "INSTAL MUDAH", "BEBAS VIRUS"] },
  { id: "app-lightroom", title: "Lightroom Classic (WIN & MAC)", category: "Design", os: "Win & Mac", versions: "2018 - 2019 - 2020 - 2021 - 2022 - 2023 - 2024 - 2025", price: 15000, originalPrice: 30000, rating: 4.8, sales: 15, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Adobe_Photoshop_Lightroom_CC_logo.svg", catalogImageUrl: "/assets/katalogLightroom.png", color: "#2563eb", specs: ["FULL VERSION", "FITUR LENGKAP", "BEBAS UPDATE", "INSTAL MUDAH", "BEBAS VIRUS"] },
  { id: "app-premiere", title: "Adobe Premiere Pro (WIN & MAC)", category: "Video", os: "Win & Mac", versions: "CS3 - CS5 - CS6 - 2015 sd 2025", price: 15000, originalPrice: 30000, rating: 4.9, sales: 22, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/40/Adobe_Premiere_Pro_CC_icon.svg", catalogImageUrl: "/assets/katalogPremiere.png", color: "#3730a3", specs: ["FULL VERSION", "FITUR LENGKAP", "BEBAS UPDATE", "INSTAL MUDAH", "BEBAS VIRUS"] },
  { id: "app-coreldraw", title: "CorelDRAW Graphics Suite 2025 (WIN)", category: "Design", os: "Windows", versions: "X6 - X7 - X8 - 2018 sd 2025", price: 15000, originalPrice: 30000, rating: 4.9, sales: 19, imageUrl: "/assets/logos/coreldraw.png", catalogImageUrl: "/assets/katalogCorel.png", color: "#16a34a", specs: ["FULL VERSION", "FITUR LENGKAP", "BEBAS UPDATE", "INSTAL MUDAH", "BEBAS VIRUS"] },
  { id: "app-recoverit", title: "Wondershare Recoverit Pro (WIN & MAC)", category: "Utility", os: "Win & Mac", versions: "Versi Terbaru 2026 Full Activated", price: 15000, originalPrice: 30000, rating: 4.8, sales: 14, imageUrl: "/assets/logos/wondershare-revocer-it.png", catalogImageUrl: "/assets/katalogRecoverit.png", color: "#0284c7", specs: ["ULTIMATE DATA RECOVERY", "SOLUSI FILE TERHAPUS", "FULL VERSION", "GARANSI"] },
  { id: "app-office", title: "Microsoft Office 365 / 2024 Pro Plus", category: "Office", os: "Win & Mac", versions: "2016 - 2019 - 2021 - 2024 - Office 365", price: 18000, originalPrice: 35000, rating: 5.0, sales: 38, imageUrl: "/assets/logos/microsoft-office.png", catalogImageUrl: "/assets/katalogMicrosoft.png", color: "#ea580c", specs: ["WORD EXCEL POWERPOINT", "FULL VERSION", "AKTIVASI PERMANEN", "UPDATE RESMI"] },
  { id: "app-idm", title: "Internet Download Manager (IDM) Lifetime", category: "Utility", os: "Windows", versions: "Versi 6.42 Build Terbaru 2026", price: 12000, originalPrice: 25000, rating: 4.9, sales: 45, imageUrl: "/assets/logos/idm.png", catalogImageUrl: "/assets/katalogIdm.png", color: "#166534", specs: ["DOWNLOAD 5X LEBIH CEPAT", "NO TRIAL POPUP", "AKTIVASI SEUMUR HIDUP"] }
];
